### ISSUE TITLE
[pomper_prime] Write an import script

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#45]
Needs to be done from the ground up

**Comment by adriansteffan** [comment]
The script passes the validator except for the xy timepoints, as there are none in the dataset (only left vs right) and the validator won't accept an empty tibble. 
How do we handle these cases? Ignore the validator? Create a dummy table with "left" and "right" xy coordinates?

**Comment by adriansteffan** [comment]
Open points that @mzettersten hopefully knows more about:

1. Is there any citation we can use for the dataset? The dataset sheet doesn't list any - did pomper publish this?

2. Do we know anything about the monitor_size, sample_rate or specific model of the tobii tracker (or can we get that through a quick email to pomper)?

**Comment by mzettersten** [comment]
1. No citation!
2. Yes. 
Monitor size: 1920 x 1080
sample_rate: The original sample rate of the eyetracker was 60 Hz, but I think the file we are handling is an integration of handcoded data with eyetracking data (because of cases where eyetracking failed), and is downsampled to 30 Hz for that reason (video recordings were only at 30 Hz).
tobii eyetracker: Tobii X2-60

So, the data is kind of a mix of eye-tracking and handcoded data - I think we can for all intents and purposes treat this as handcoded.

**Comment by adriansteffan** [comment]
I fixed these, this dataset still has the stimuli table bug, leaving it open until I fix it
