### ISSUE TITLE
[attword] [attword_processed] Update import script ?

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#55]
There is no osf data for attword_processed - is there only one dataset? What happened? 

The scripts for both attword_processed and attword are outdated - missing the aux column.

**Comment by adriansteffan** [comment]
@mzettersten Maybe you know what happened here?

**Comment by JMankewitz** [comment]
I suspect what happened is the folder "attword" was once called "attword_processed" and was changed for clarity. 

Related, attword has always been tricky because the target side/label is determined by both the trial type (e.g., a mutual exclusivity trial vs an unambiguous trial) and also the experiment type (Saliency), neither of which are clearly documented. Historically this caused some confusion about novel vs familiar labels (see https://github.com/langcog/peekbank-data-import/issues/16) 

I just pushed some edits (https://github.com/langcog/peekbank-data-import/commit/04e9cd59cbb2bbb3bb57992d74e4659cb41e4984#diff-3675d52278ab3a156610b4f4516f0e7b8390be059f4635b449714b4e3c6dadca) I made trying to detangle these based on the paper's descriptions of trial orders, but I made note of many assumptions...

@kachergis and @cbergey and I are probably best to direct questions to as you work through this one!

**Comment by adriansteffan** [comment]
Thanks for the heads-up and the changes! 

I updated the script so that the data passes the 3.0 validator, and given that there doesn't seem to be any cdi data, this should be in the v2024 schema now. It might be worth it to have another look at the design during the review stage for the dataset. I will tackle the open issues with simulus familiarity right after this.

Keeping the issue open until these two points are resolved:

1. Seeing that this is actually "yurovsky_2017", it might make sense to rename the dataset in git and osf?

2. As "attword" seems to be dead then, we can remove it from the git repo as well. We can always restore it from git history if we need it after all.

**Comment by adriansteffan** [comment]
> Thanks for the heads-up and the changes!
> 
> I updated the script so that the data passes the 3.0 validator, and given that there doesn't seem to be any cdi data, this should be in the v2024 schema now. It might be worth it to have another look at the design during the review stage for the dataset. I will tackle the open issues with simulus familiarity right after this.
> 
> Keeping the issue open until these two points are resolved:
> 
> 1. Seeing that this is actually "yurovsky_2017", it might make sense to rename the dataset in git and osf?
> 2. As "attword" seems to be dead then, we can remove it from the git repo as well. We can always restore it from git history if we need it after all.

done
