### ISSUE TITLE
double-check distractor stimuli in tables

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#71]
For the stimulus table, distractors get their own row. The label for the distractors should be the label that is provided for *that image* in the experiment (when it is in target position). If the image *never* appears in target position, the label is *either*:

- the label given to the image in the experiment description (e.g., "the distractor was an image of a chair")
- if there is no obvious label provided in the experiment design, leave label blank

**Comment by adriansteffan** [comment]
Fixed the ones I knew were broken, now we would need to go through all the datasets and check how this was handled. As this requires some digging into the designs (mostly: was every distractor image also present as a target at some point?) we could think about moving this into the general code review step instead of doing it on its own
